// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGHv5hR4EPiTE5aW6YcUGoDoN2cglRPR8',
    appId: '1:613334440308:android:fa9ae63f71c7c24760f421',
    messagingSenderId: '613334440308',
    projectId: 'book-a-table-ef785',
    storageBucket: 'book-a-table-ef785.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWiFiC46-xBPLFj1Engf1xrmRlt9IZ3do',
    appId: '1:613334440308:ios:d1fde92a47896d7560f421',
    messagingSenderId: '613334440308',
    projectId: 'book-a-table-ef785',
    storageBucket: 'book-a-table-ef785.appspot.com',
    iosClientId: '613334440308-jgsmbuu5uvdrmi6ls2a0b1d958pii34c.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookATable',
  );
}
